export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';

/*ClassAttendance.jsx*/
export const UPDATE_CLASS_ATTENDANCE = 'UPDATE_CLASS_ATTENDANCE';
export const LIST_SEARCH_CLASS_ATTENDANCE = 'LIST_SEARCH_CLASS_ATTENDANCE'
export const LIST_REPORT_ATTENDANCE = 'LIST_REPORT_ATTENDANCE'

/*Student.jsx*/
export const GET_STUDENT_NO_BY_CLASS_ATTENDANCE_STUDENT_KEY_CODE_NAME = 'GET_STUDENT_NO_BY_CLASS_ATTENDANCE_STUDENT_KEY_CODE_NAME';
export const LIST_SEARCH_STUDENT1 = 'LIST_SEARCH_STUDENT1'
export const GET_STUDENT_NO_BY_STUDENT_CODE_NAME = 'GET_STUDENT_NO_BY_STUDENT_CODE_NAME'
export const CHECK_STUDENT_CODE_NAME = 'CHECK_STUDENT_CODE_NAME'
export const EDIT_STUDENT = 'EDIT_STUDENT'
export const EDIT_STUDENT_NO_IMG_EDIT = 'EDIT_STUDENT_NO_IMG_EDIT'
export const ADD_STUDENT = 'ADD_STUDENT'
export const LIST_SEARCH_STUDENT = 'LIST_SEARCH_STUDENT'

/*Semester.jsx*/
export const LIST_SEMESTER = 'LIST_SEMESTER'
export const CHECK_SEMESTER_NAME = 'CHECK_SEMESTER_NAME'
export const EDIT_SEMESTER = 'EDIT_SEMESTER'
export const ADD_SEMESTER = 'ADD_SEMESTER'
export const LIST_SEMESTER_SEARCH = 'LIST_SEMESTER_SEARCH'

/*Subject.jsx*/
export const LIST_SUBJECT = 'LIST_SUBJECT'
export const CHECK_SUBJECT_ID = 'CHECK_SUBJECT_ID'
export const EDIT_SUBJECT = 'EDIT_SUBJECT'
export const ADD_SUBJECT = 'ADD_SUBJECT'
export const LIST_SEARCH_SUBJECT = 'LIST_SEARCH_SUBJECT'

/*UserType.jsx*/
export const LIST_PERMISSION = 'LIST_PERMISSION'
export const EDIT_PERMISSION = 'EDIT_PERMISSION'
export const GET_PERMISSION_DETAIL = 'GET_PERMISSION_DETAIL'
export const LIST_PERMISSION_ALL = 'LIST_PERMISSION_ALL'

/* Login.jsx*/
export const WRITE_LOG_LOGIN = 'WRITE_LOG_LOGIN'
export const WRITE_LOG_LOGIN_ERROR = 'WRITE_LOG_LOGIN_ERROR'
export const LIST_REPORT_TRANSACTION = 'LIST_REPORT_TRANSACTION'
export const WRITE_LOG_LOGOUT= 'WRITE_LOG_LOGOUT'
export const GET_USER_NAME = 'GET_USER_NAME'

/*User.jsx*/
export const CHECK_USER_LOGIN = 'CHECK_USER_LOGIN'
export const CHECK_USER_PASSWORD = 'CHECK_USER_PASSWORD'
export const CHECK_USER_STATUS = 'CHECK_USER_STATUS'
export const GET_USER_NO = 'GET_USER_NO'
export const GET_INACTIVE_INFO = 'GET_INACTIVE_INFO'
export const EDIT_USER = 'EDIT_USER'
export const ADD_USER = 'ADD_USER'
export const SEARCH_USER = 'SEARCH_USER'

/*Report.jsx*/
export const DISPLAY_REPORT_ATTENDANCE = 'DISPLAY_REPORT_ATTENDANCE'
export const DISPLAY_REPORT_TRANSACTION = 'DISPLAY_REPORT_TRANSACTION'

/*Teacher.jsx*/
export const LIST_TEACHER = 'LIST_TEACHER'
export const CHECK_TEACHER_FIRST_NAME_AND_LAST_NAME = 'CHECK_TEACHER_FIRST_NAME_AND_LAST_NAME'
export const EDIT_TEACHER = 'EDIT_TEACHER'
export const ADD_TEACHER = 'ADD_TEACHER'
export const LIST_SEARCH_TEACHER = 'LIST_SEARCH_TEACHER'

/*Menu.jsx*/
export const SET_PERMISSION = 'SET_PERMISSION'